const DATE_DELIMITER = '-';

const appConstants = {
    DATE_DELIMITER: DATE_DELIMITER,
    DATE_FORMAT_STRING: `YYYY${DATE_DELIMITER}MM${DATE_DELIMITER}DD`,
    STANDARD_OPERATION: 'STANDARD_OPERATION',
    NTH_WEEKDAYS_OF_MONTH:  'NTH_WEEKDAYS_OF_MONTH',
    WEEKDAY_ON_DATE: 'WEEKDAY_ON_DATE',
    MOVE_THIS_PARTICULAR_PROCESS_DATE_AFTER_THESE_WEEKDAYS: 'MOVE_THIS_PARTICULAR_PROCESS_DATE_AFTER_THESE_WEEKDAYS',
    MOVE_THIS_PARTICULAR_PROCESS_DATE_AFTER_THESE_DATES: 'MOVE_THIS_PARTICULAR_PROCESS_DATE_AFTER_THESE_DATES',
    ADJUST_AMOUNT_ON_THESE_PARTICULAR_DATES: 'ADJUST_AMOUNT_ON_THESE_PARTICULAR_DATES',
    ANNUALLY: 'ANNUALLY',
    MONTHLY: 'MONTHLY',
    WEEKLY: 'WEEKLY',
    DAILY: 'DAILY',
    ONCE: 'ONCE',
    SUNDAY_NUM: 0,
    MONDAY_NUM: 1,
    TUESDAY_NUM: 2,
    WEDNESDAY_NUM: 3,
    THURSDAY_NUM: 4,
    FRIDAY_NUM: 5,
    SATURDAY_NUM: 6,
    DISCOVERING_OPERATION_TYPE: 'DISCOVERING_OPERATION_TYPE',
    EVALUATING_RULE_INSERTION: 'EVALUATING_RULE_INSERTION',
    EXECUTING_RULE_INSERTION: 'EXECUTING_RULE_INSERTION',
    EXECUTING_RULE_ADJUSTMENT: 'EXECUTING_RULE_ADJUSTMENT',
    MODIFIED: 'MODIFIED',
    RETIRING_RULES: 'RETIRING_RULES',
    STANDARD_TERMINAL_OUTPUT: 'STANDARD_TERMINAL_OUTPUT',
    VERBOSE: 'VERBOSE',
    CONCISE: 'CONCISE',
    NOT_AVAILABLE: 'N/A',
    BUILD_DATE_STRING: ({ year, month, day }) => {
        return `${year}${DATE_DELIMITER}${month}${DATE_DELIMITER}${day}`;
    }
};

module.exports = appConstants;
